apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
  - name: {{ .Values.name }}
    protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}
